version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    ports:
      - "127.0.0.1:6009:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=r00t
      - POSTGRES_DB=todo-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: r00t
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data: